### ISSUE TITLE
File doesn't load

### ISSUE THREAD

**Issue by carlossarmiento19** [alexanderadavid/Myo-HMI-Android#21]
Hi!!

when I try to load the file with the trained gestures this doesn´t load and the bluetooth disconnects.
how can I solve that?

Thanks in advance.

**Comment by alexanderadavid** [comment]
Hi Carlos,

It's great to hear that people are trying our gesture recognition app!

Can I have some more information about the process leading up to the bug?

I'm assuming you trained some gestures then exported the file through the application. Then, when importing the file, your bluetooth disconnects?

Thanks!

**Comment by carlossarmiento19** [comment]
Yes, that's exactly what happens
But i don't know to solve that
Thanks!

**Comment by alexanderadavid** [comment]
This has been resolved
